# name: Frontend CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16

#       - name: Install Dependencies
#         run: cd /client && npm install

#       - name: Build Frontend
#         run: npm run build

#       - name: Upload to S3
#         env:
#           AWS_ACCESS_KEY_ID: AKIAQD6AUEVRYSG536HJ
#           AWS_SECRET_ACCESS_KEY: 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
#         run: npm run prod


name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: cd /client && npm install

      - name: Run Production Build
        run: cd /client && npm run prod

      - name: Upload to S3
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp /client/build/ s3://your-s3-bucket-name/ --recursive
